lesson1

In [60]:
import numpy as np
import pandas as pd

In [4]:
a = np.array([[1, 6],[2, 8], [3, 11], [3, 10], [1, 7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [6]:
mean_a = a.mean(axis = 0)
print('Среднее значение по признаку, ', mean_a )

Среднее значение по признаку,  [2.  8.4]


In [8]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [17]:
a_centered_sp = np.dot(a[:, 1], a[:, 1:2])
print(a_centered_sp)

[370]


In [19]:
N = a.shape[1]
print(N)

2


In [20]:
D = a_centered_sp / (N-1)
print(D)

[370.]


In [22]:
a_transpose = a.transpose()
print(a_transpose)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [23]:
C = np.cov(a_transpose)
print(C)

[[1.  2. ]
 [2.  4.3]]


In [26]:
C_cov = C[:1, 1:2]
print(C_cov)

[[2.]]


In [29]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 
                       'author_name':['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [30]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price':[450, 300, 350, 500, 450, 370, 290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [31]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner' )
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [33]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [41]:
authors_max = authors_price.groupby('author_name').agg({'price': 'max'})
authors_max = authors_max.rename(columns={'price':'max_price'})
authors_min = authors_price.groupby('author_name').agg({'price': 'min'})
authors_min = authors_min.rename(columns={'price':'min_price'})
authors_mean = authors_price.groupby('author_name').agg({'price': 'mean'})
authors_mean = authors_mean.rename(columns={'price':'mean_price'})
authors_stat = pd.concat([authors_max, authors_min, authors_mean], axis = 1)
authors_stat

max_price  min_price  mean_price
author_name                                  
Островский         370        290  330.000000
Тургенев           450        300  366.666667
Чехов              500        450  475.000000

In [42]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [65]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'],
                    columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info 

TypeError: 'tuple' object is not callable

In [66]:
book_info.to_pickle('book_info.pkl')

NameError: name 'book_info' is not defined

In [67]:
book_info2 = pd.read_pickle('book_info.pkl')


FileNotFoundError: [Errno 2] No such file or directory: 'book_info.pkl'

In [ ]:
book_info==book_info2